
replicaCount: 1
image:
  repository: ghcr.io/otrokov
  tag: "v1.0.9-990ce02"
  os: "linux"
  arch: "amd64"
secret:
  name: "currencybot"
  tokenname: "TELE_TOKEN"
  tokenkey: "token"
securityContext:
  privileged: true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
